@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe SMTNameplate

class "Nameplate" as ID00000001 <<SM>> {
  +URIOfTheProduct : xs:string = "https://www...."
  +ManufacturerName : MLP = "Muster AG"
  +ManufacturerProductDesignation : MLP = "ABC-123"
  +ManufacturerProductRoot : MLP [0..1] = "flow meter"
  +ManufacturerProductFamily : MLP [0..1] = "Type ABC"
  +ManufacturerProductType : MLP [0..1] = "FM-ABC-1234"
  +OrderCodeOfManufacturer : MLP [0..1] = "FMABC1234"
  +ProductArticleNumberOfManufacturer : MLP [0..1] = "FM11-ABC22-1..."
  +SerialNumber : xs:string [0..1] = "12345678"
  +YearOfConstruction : xs:string = "2022"
  +DateOfManufacture : xs:date [0..1] = "2022-01-01"
  +HardwareVersion : MLP [0..1] = "1.0.0"
  +FirmwareVersion : MLP [0..1] = "1.0"
  +SoftwareVersion : MLP [0..1] = "1.0.0"
  +CountryOfOrigin : xs:string [0..1] = "DE"
  +CompanyLogo : File [0..1]
  +Markings : SML [0..1]
}

class "Markings" as ID00000002 <<SML>> {
  +[00] : SMC
  +[01] : SMC
}

class "[00]" as ID00000003 <<SMC>> {
  +MarkingName : xs:string = "0173-1#07-DA..."
  +DesignationOfCertificateOrApproval : xs:string [0..1] = "KEMA99IECEX1..."
  +IssueDate : xs:string [0..1] = "2022-01-01"
  +ExpiryDate : xs:string [0..1] = "2022-01-01"
  +MarkingFile : File
  +MarkingAdditionalText : xs:string [0..*] = "0044"
}

class "[01]" as ID00000004 <<SMC>> {
  +MarkingName : xs:string = "0173-1#07-DA..."
  +DesignationOfCertificateOrApproval : xs:string [0..1] = "KEMA99IECEX1..."
  +IssueDate : xs:string [0..1] = "2022-01-01"
  +ExpiryDate : xs:string [0..1] = "2022-01-01"
  +MarkingFile : File
  +MarkingAdditionalText : xs:string [0..*] = "0044"
}

ID00000002 *--  ID00000003 : "[00]"
ID00000002 *--  ID00000004 : "[01]"
ID00000001 *-- "0..1" ID00000002 : "Markings"
@enduml
